### PR TITLE
Initial migration of a snow17 FORTRAN source code into the OWP Snow17 repository

### PR DESCRIPTION
**Pull request by andywood**

### CODE REVIEW

**Comment by andywood** [comment]
This PR contains an adapted version of the original Snow17SacUH code that has had all the Sac & UH functionality stripped out so that the driver only runs the Snow17 model.  It includes a test case for the Flathead River inflows to Hungry Horse reservoir made up of two snow bands.  It was debugged, and compiled and ran with the gfortran compiler on Cheyenne.

**Comment by SnowHydrology** [comment]
@andywood The code runs for me with some mods to the makefile. At first the model wouldn't build. I tracked the issue down here:

```
# compile calibration code
model:
	$(FC77) $(FLAGS77) -c $(calib_pgf77) $(INC77)
	$(FC) $(FLAGS2) -c $(calib_pgf90_2) $(INC)
	$(FC) $(FLAGS) -c $(calib_pgf90) $(DRIVER) \
	$(INC)
```

`calib_pgf77` is undefined in the makefile. Are the Fortran77 lines remnants from a previous Snow-17 version? If so, it looks like most of them can be deleted. I will do that if you confirm they're not needed.

**Comment by andywood** [comment]
I think this is a line I should have deleted related to compiling the sac
or duamel / routing part of the code that has since been deleted.
I'll confirm and update the PR.  thanks!

**Comment by andywood** [comment]
I removed those f77 lines and retested both the regular and debug compilations using gfortran on cheyenne.

**Pull request merged**
